### ISSUE TITLE
Missing nested stack templates

### ISSUE THREAD

**Issue by nosnilmot** [wso2/aws-is#103]
**Description:**
Nested stacks referenced by the minimal template are missing from S3

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
WSO2 5.11.0 Identity Server Minimal/Basic AWS Cloudformation template (https://aws-nested-cloudformation-iam.s3.amazonaws.com/wso2is-5.11.0/nested-identity-minimal.yaml)

**OS, DB, other environment details and versions:**    
AWS Cloudformation

**Steps to reproduce:**

Try to deploy Cloudformation stack using https://aws-nested-cloudformation-iam.s3.amazonaws.com/wso2is-5.11.0/nested-identity.yaml
Deployment will fail with "access denied" error when attempting to download network stack, because template does not exist. Database and Identity stacks are also missing:
https://aws-nested-cloudformation.s3.amazonaws.com/wso2is-5.11.0/network.yaml
https://aws-nested-cloudformation.s3.amazonaws.com/wso2is-5.11.0/database.yaml
https://aws-nested-cloudformation.s3.amazonaws.com/wso2is-5.11.0/identity.yaml

**Related Issues:**

**Comment by madurangasiriwardena** [comment]
Closing the issue due to the inactivity of the repository.
