### ISSUE TITLE
Missing WSO2 PuppetMaster AMIs

### ISSUE THREAD

**Issue by nosnilmot** [wso2/aws-is#104]
**Description:**
AMIs referenced in the S3 CloudFormation template do not exist.

None of the AMIs in the WSO2PuppetMasterRegionMap in https://aws-nested-cloudformation-iam.s3.amazonaws.com/wso2is-5.11.0/identity.yaml exist in AWS.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
WSO2 Identity Server 5.11.0 Full/Advanced CloudFormation stack

**OS, DB, other environment details and versions:**    
AWS CloudFormation

**Steps to reproduce:**

Try to deploy WSO2 Identity Server 5.11.0 using Full/Advanced CloudFormation stack. Deployment fails with error:
```The image id '[ami-0de587e8d1a30f15d]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound; Request ID: 877d899d-c13b-4346-a428-c4c54e8d98d4; Proxy: null)```

It can be verified that none of the images exist:
```
$ aws ec2 describe-images --region ap-southeast-2 --image-ids ami-0bb8ccb83187137b7

An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-0bb8ccb83187137b7]' does not exist
$ aws ec2 describe-images --region eu-west-1 --image-ids ami-045ef4eb960d05a5d

An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-045ef4eb960d05a5d]' does not exist
$ aws ec2 describe-images --region us-east-1 --image-ids ami-0de587e8d1a30f15d

An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-0de587e8d1a30f15d]' does not exist
$ aws ec2 describe-images --region us-east-2 --image-ids ami-0b7d512d97bcf418f

An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-0b7d512d97bcf418f]' does not exist
$ aws ec2 describe-images --region us-west-1 --image-ids ami-01caec704e037d3b0

An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-01caec704e037d3b0]' does not exist
$ aws ec2 describe-images --region us-west-2 --image-ids ami-08f29412528a3056d

An error occurred (InvalidAMIID.NotFound) when calling the DescribeImages operation: The image id '[ami-08f29412528a3056d]' does not exist

```

There is no evidence of those AMIs ever having been included in the git version of identity.yaml either:

```
$ git log -S ami-0de587e8d1a30f15d product/identity.yaml
$
```

**Related Issues:**

**Comment by madurangasiriwardena** [comment]
Closing the issue due to the inactivity of the repository.
